name: YaMDb Final

on: [push]

jobs:
  check_code:
    name: Tests by Flake8 & Pytest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r api_yamdb/requirements.txt

    - name: Test with flake8 and pytest
      run: |
        python -m flake8
        pytest

  build_image:
    name: Push Image to Docker Hub
    runs-on: ubuntu-latest
    needs: check_code

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ SECRETS.DOCKER_PASSWORD }}

    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: api_yamdb/
        push: true
        tags: sivikgosh/api_yamdb

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build_image

    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          sudo docker pull sivikgosh/api_yamdb
          cd yamdb_final/infra/
          sudo docker-compose up -d --build

  send_notification:
    name: Send message to Telegram
    runs-on: ubuntu-latest
    needs: deploy

    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} выполнен.
