# Generated by Django 2.2.16 on 2022-11-13 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genretitle',
            options={'ordering': ['-id'], 'verbose_name': 'Жанр - Произведение', 'verbose_name_plural': 'Жанры - Произведения'},
        ),
    ]
